package wad

type Currency struct {
	Code      string `json:"code"`
	Countries string `json:"countries"`
	Decimals  int    `json:"decimals"`
	// negative if null
	IsoNum int    `json:"iso_num"`
	Name   string `json:"name"`
	Symbol string `json:"symbol"`
}

type CurrencyMap = map[string]Currency

var Fiat = CurrencyMap{
	"AED": {
		Code:      "AED",
		Countries: "United Arab Emirates",
		Decimals:  2,
		IsoNum:    784,
		Name:      "United Arab Emirates dirham",
		Symbol:    "د.إ",
	},
	"AFN": {
		Code:      "AFN",
		Countries: "Afghanistan",
		Decimals:  2,
		IsoNum:    971,
		Name:      "Afghan afghani",
		Symbol:    "",
	},
	"ALL": {
		Code:      "ALL",
		Countries: "Albania",
		Decimals:  2,
		IsoNum:    8,
		Name:      "Albanian lek",
		Symbol:    "L",
	},
	"AMD": {
		Code:      "AMD",
		Countries: "Armenia",
		Decimals:  2,
		IsoNum:    51,
		Name:      "Armenian dram",
		Symbol:    "",
	},
	"ANG": {
		Code:      "ANG",
		Countries: "Curaçao (CW), Sint Maarten (SX)",
		Decimals:  2,
		IsoNum:    532,
		Name:      "Netherlands Antillean guilder",
		Symbol:    "ƒ",
	},
	"AOA": {
		Code:      "AOA",
		Countries: "Angola",
		Decimals:  2,
		IsoNum:    973,
		Name:      "Angolan kwanza",
		Symbol:    "Kz",
	},
	"ARS": {
		Code:      "ARS",
		Countries: "Argentina",
		Decimals:  2,
		IsoNum:    32,
		Name:      "Argentine peso",
		Symbol:    "$",
	},
	"AUD": {
		Code:      "AUD",
		Countries: "Australia, Christmas Island (CX), Cocos (Keeling) Islands (CC), Heard Island and McDonald Islands (HM), Kiribati (KI), Nauru (NR), Norfolk Island (NF), Tuvalu (TV)",
		Decimals:  2,
		IsoNum:    36,
		Name:      "Australian dollar",
		Symbol:    "$",
	},
	"AWG": {
		Code:      "AWG",
		Countries: "Aruba",
		Decimals:  2,
		IsoNum:    533,
		Name:      "Aruban florin",
		Symbol:    "ƒ",
	},
	"AZN": {
		Code:      "AZN",
		Countries: "Azerbaijan",
		Decimals:  2,
		IsoNum:    944,
		Name:      "Azerbaijani manat",
		Symbol:    "₼",
	},
	"BAM": {
		Code:      "BAM",
		Countries: "Bosnia and Herzegovina",
		Decimals:  2,
		IsoNum:    977,
		Name:      "Bosnia and Herzegovina convertible mark",
		Symbol:    "KM",
	},
	"BBD": {
		Code:      "BBD",
		Countries: "Barbados",
		Decimals:  2,
		IsoNum:    52,
		Name:      "Barbados dollar",
		Symbol:    "Bds$",
	},
	"BDT": {
		Code:      "BDT",
		Countries: "Bangladesh",
		Decimals:  2,
		IsoNum:    50,
		Name:      "Bangladeshi taka",
		Symbol:    "৳",
	},
	"BGN": {
		Code:      "BGN",
		Countries: "Bulgaria",
		Decimals:  2,
		IsoNum:    975,
		Name:      "Bulgarian lev",
		Symbol:    "лв",
	},
	"BHD": {
		Code:      "BHD",
		Countries: "Bahrain",
		Decimals:  3,
		IsoNum:    48,
		Name:      "Bahraini dinar",
		Symbol:    ".د.ب",
	},
	"BIF": {
		Code:      "BIF",
		Countries: "Burundi",
		Decimals:  0,
		IsoNum:    108,
		Name:      "Burundian franc",
		Symbol:    "FBu",
	},
	"BMD": {
		Code:      "BMD",
		Countries: "Bermuda",
		Decimals:  2,
		IsoNum:    60,
		Name:      "Bermudian dollar",
		Symbol:    "BD$",
	},
	"BND": {
		Code:      "BND",
		Countries: "Brunei",
		Decimals:  2,
		IsoNum:    96,
		Name:      "Brunei dollar",
		Symbol:    "B$",
	},
	"BOB": {
		Code:      "BOB",
		Countries: "Bolivia",
		Decimals:  2,
		IsoNum:    68,
		Name:      "Boliviano",
		Symbol:    "Bs",
	},
	"BRL": {
		Code:      "BRL",
		Countries: "Brazil",
		Decimals:  2,
		IsoNum:    986,
		Name:      "Brazilian real",
		Symbol:    "R$",
	},
	"BSD": {
		Code:      "BSD",
		Countries: "Bahamas",
		Decimals:  2,
		IsoNum:    44,
		Name:      "Bahamian dollar",
		Symbol:    "B$",
	},
	"BTN": {
		Code:      "BTN",
		Countries: "Bhutan",
		Decimals:  2,
		IsoNum:    64,
		Name:      "Bhutanese ngultrum",
		Symbol:    "Nu.",
	},
	"BWP": {
		Code:      "BWP",
		Countries: "Botswana",
		Decimals:  2,
		IsoNum:    72,
		Name:      "Botswana pula",
		Symbol:    "P",
	},
	"BYN": {
		Code:      "BYN",
		Countries: "Belarus",
		Decimals:  2,
		IsoNum:    933,
		Name:      "Belarusian ruble",
		Symbol:    "Br",
	},
	"BZD": {
		Code:      "BZD",
		Countries: "Belize",
		Decimals:  2,
		IsoNum:    84,
		Name:      "Belize dollar",
		Symbol:    "BZ$",
	},
	"CAD": {
		Code:      "CAD",
		Countries: "Canada",
		Decimals:  2,
		IsoNum:    124,
		Name:      "Canadian dollar",
		Symbol:    "$",
	},
	"CDF": {
		Code:      "CDF",
		Countries: "Democratic Republic of the Congo",
		Decimals:  2,
		IsoNum:    976,
		Name:      "Congolese franc",
		Symbol:    "FC",
	},
	"CHF": {
		Code:      "CHF",
		Countries: "Switzerland, Liechtenstein (LI)",
		Decimals:  2,
		IsoNum:    756,
		Name:      "Swiss franc",
		Symbol:    "SFr",
	},
	"CLF": {
		Code:      "CLF",
		Countries: "Chile",
		Decimals:  4,
		IsoNum:    990,
		Name:      "Unidad de Fomento (funds Code)",
		Symbol:    "UF",
	},
	"CLP": {
		Code:      "CLP",
		Countries: "Chile",
		Decimals:  0,
		IsoNum:    152,
		Name:      "Chilean peso",
		Symbol:    "$",
	},
	"CNY": {
		Code:      "CNY",
		Countries: "China",
		Decimals:  2,
		IsoNum:    156,
		Name:      "Chinese yuan",
		Symbol:    "¥",
	},
	"COP": {
		Code:      "COP",
		Countries: "Colombia",
		Decimals:  2,
		IsoNum:    170,
		Name:      "Colombian peso",
		Symbol:    "$",
	},
	"CRC": {
		Code:      "CRC",
		Countries: "Costa Rica",
		Decimals:  2,
		IsoNum:    188,
		Name:      "Costa Rican colon",
		Symbol:    "₡",
	},
	"CUP": {
		Code:      "CUP",
		Countries: "Cuba",
		Decimals:  2,
		IsoNum:    192,
		Name:      "Cuban peso",
		Symbol:    "$",
	},
	"CVE": {
		Code:      "CVE",
		Countries: "Cabo Verde",
		Decimals:  2,
		IsoNum:    132,
		Name:      "Cape Verdean escudo",
		Symbol:    "$",
	},
	"CZK": {
		Code:      "CZK",
		Countries: "Czechia",
		Decimals:  2,
		IsoNum:    203,
		Name:      "Czech koruna",
		Symbol:    "Kč",
	},
	"DJF": {
		Code:      "DJF",
		Countries: "Djibouti",
		Decimals:  0,
		IsoNum:    262,
		Name:      "Djiboutian franc",
		Symbol:    "Fdj",
	},
	"DKK": {
		Code:      "DKK",
		Countries: "Denmark, Faroe Islands (FO), Greenland (GL)",
		Decimals:  2,
		IsoNum:    208,
		Name:      "Danish krone",
		Symbol:    "kr.",
	},
	"DOP": {
		Code:      "DOP",
		Countries: "Dominican Republic",
		Decimals:  2,
		IsoNum:    214,
		Name:      "Dominican peso",
		Symbol:    "$",
	},
	"DZD": {
		Code:      "DZD",
		Countries: "Algeria",
		Decimals:  2,
		IsoNum:    12,
		Name:      "Algerian dinar",
		Symbol:    "دج",
	},
	"EGP": {
		Code:      "EGP",
		Countries: "Egypt",
		Decimals:  2,
		IsoNum:    818,
		Name:      "Egyptian pound",
		Symbol:    "E£",
	},
	"ERN": {
		Code:      "ERN",
		Countries: "Eritrea",
		Decimals:  2,
		IsoNum:    232,
		Name:      "Eritrean nakfa",
		Symbol:    "Nkf",
	},
	"ETB": {
		Code:      "ETB",
		Countries: "Ethiopia",
		Decimals:  2,
		IsoNum:    230,
		Name:      "Ethiopian birr",
		Symbol:    "Br",
	},
	"EUR": {
		Code:      "EUR",
		Countries: "Åland Islands (AX), European Union (EU), Andorra (AD), Austria (AT), Belgium (BE), Cyprus (CY), Estonia (EE), Finland (FI), France (FR), French Southern and Antarctic Lands (TF), Germany (DE), Greece (GR), Guadeloupe (GP), Ireland (IE), Italy (IT), Latvia (LV), Lithuania (LT), Luxembourg (LU), Malta (MT), French Guiana (GF), Martinique (MQ), Mayotte (YT), Monaco (MC), Montenegro (ME), Netherlands (NL), Portugal (PT), Réunion (RE), Saint Barthélemy (BL), Saint Martin (MF), Saint Pierre and Miquelon (PM), San Marino (SM), Slovakia (SK), Slovenia (SI), Spain (ES), Vatican City (VA)",
		Decimals:  2,
		IsoNum:    978,
		Name:      "Euro",
		Symbol:    "€",
	},
	"FJD": {
		Code:      "FJD",
		Countries: "Fiji",
		Decimals:  2,
		IsoNum:    242,
		Name:      "Fiji dollar",
		Symbol:    "FJ$",
	},
	"FKP": {
		Code:      "FKP",
		Countries: "Falkland Islands (pegged to GBP 1:1)",
		Decimals:  2,
		IsoNum:    238,
		Name:      "Falkland Islands pound",
		Symbol:    "£",
	},
	"GBP": {
		Code:      "GBP",
		Countries: "United Kingdom, the Isle of Man (IM, see Manx pound), Jersey (JE, see Jersey pound), and Guernsey (GG, see Guernsey pound)",
		Decimals:  2,
		IsoNum:    826,
		Name:      "Pound sterling",
		Symbol:    "£",
	},
	"GEL": {
		Code:      "GEL",
		Countries: "Georgia",
		Decimals:  2,
		IsoNum:    981,
		Name:      "Georgian lari",
		Symbol:    "₾",
	},
	"GHS": {
		Code:      "GHS",
		Countries: "Ghana",
		Decimals:  2,
		IsoNum:    936,
		Name:      "Ghanaian cedi",
		Symbol:    "GH₵",
	},
	"GIP": {
		Code:      "GIP",
		Countries: "Gibraltar (pegged to GBP 1:1)",
		Decimals:  2,
		IsoNum:    292,
		Name:      "Gibraltar pound",
		Symbol:    "£",
	},
	"GMD": {
		Code:      "GMD",
		Countries: "Gambia",
		Decimals:  2,
		IsoNum:    270,
		Name:      "Gambian dalasi",
		Symbol:    "D",
	},
	"GNF": {
		Code:      "GNF",
		Countries: "Guinea",
		Decimals:  0,
		IsoNum:    324,
		Name:      "Guinean franc",
		Symbol:    "FG",
	},
	"GTQ": {
		Code:      "GTQ",
		Countries: "Guatemala",
		Decimals:  2,
		IsoNum:    320,
		Name:      "Guatemalan quetzal",
		Symbol:    "Q",
	},
	"GYD": {
		Code:      "GYD",
		Countries: "Guyana",
		Decimals:  2,
		IsoNum:    328,
		Name:      "Guyanese dollar",
		Symbol:    "G$",
	},
	"HKD": {
		Code:      "HKD",
		Countries: "Hong Kong",
		Decimals:  2,
		IsoNum:    344,
		Name:      "Hong Kong dollar",
		Symbol:    "HK$",
	},
	"HNL": {
		Code:      "HNL",
		Countries: "Honduras",
		Decimals:  2,
		IsoNum:    340,
		Name:      "Honduran lempira",
		Symbol:    "L",
	},
	"HRK": {
		Code:      "HRK",
		Countries: "Croatia",
		Decimals:  2,
		IsoNum:    191,
		Name:      "Croatian kuna",
		Symbol:    "kn",
	},
	"HTG": {
		Code:      "HTG",
		Countries: "Haiti",
		Decimals:  2,
		IsoNum:    332,
		Name:      "Haitian gourde",
		Symbol:    "G",
	},
	"HUF": {
		Code:      "HUF",
		Countries: "Hungary",
		Decimals:  2,
		IsoNum:    348,
		Name:      "Hungarian forint",
		Symbol:    "Ft",
	},
	"IDR": {
		Code:      "IDR",
		Countries: "Indonesia",
		Decimals:  2,
		IsoNum:    360,
		Name:      "Indonesian rupiah",
		Symbol:    "Rp",
	},
	"ILS": {
		Code:      "ILS",
		Countries: "Israel",
		Decimals:  2,
		IsoNum:    376,
		Name:      "Israeli new shekel",
		Symbol:    "₪",
	},
	"INR": {
		Code:      "INR",
		Countries: "India, Bhutan",
		Decimals:  2,
		IsoNum:    356,
		Name:      "Indian rupee",
		Symbol:    "₹",
	},
	"IQD": {
		Code:      "IQD",
		Countries: "Iraq",
		Decimals:  3,
		IsoNum:    368,
		Name:      "Iraqi dinar",
		Symbol:    "د.ع",
	},
	"IRR": {
		Code:      "IRR",
		Countries: "Iran",
		Decimals:  2,
		IsoNum:    364,
		Name:      "Iranian rial",
		Symbol:    "﷼",
	},
	"ISK": {
		Code:      "ISK",
		Countries: "Iceland",
		Decimals:  0,
		IsoNum:    352,
		Name:      "Icelandic króna",
		Symbol:    "kr",
	},
	"JMD": {
		Code:      "JMD",
		Countries: "Jamaica",
		Decimals:  2,
		IsoNum:    388,
		Name:      "Jamaican dollar",
		Symbol:    "J$",
	},
	"JOD": {
		Code:      "JOD",
		Countries: "Jordan",
		Decimals:  3,
		IsoNum:    400,
		Name:      "Jordanian dinar",
		Symbol:    "$",
	},
	"JPY": {
		Code:      "JPY",
		Countries: "Japan",
		Decimals:  0,
		IsoNum:    392,
		Name:      "Japanese yen",
		Symbol:    "د.أ",
	},
	"KES": {
		Code:      "KES",
		Countries: "Kenya",
		Decimals:  2,
		IsoNum:    404,
		Name:      "Kenyan shilling",
		Symbol:    "$",
	},
	"KGS": {
		Code:      "KGS",
		Countries: "Kyrgyzstan",
		Decimals:  2,
		IsoNum:    417,
		Name:      "Kyrgyzstani som",
		Symbol:    "KSh",
	},
	"KHR": {
		Code:      "KHR",
		Countries: "Cambodia",
		Decimals:  2,
		IsoNum:    116,
		Name:      "Cambodian riel",
		Symbol:    "С̲",
	},
	"KMF": {
		Code:      "KMF",
		Countries: "Comoros",
		Decimals:  0,
		IsoNum:    174,
		Name:      "Comoro franc",
		Symbol:    "៛",
	},
	"KPW": {
		Code:      "KPW",
		Countries: "North Korea",
		Decimals:  2,
		IsoNum:    408,
		Name:      "North Korean won",
		Symbol:    "₩",
	},
	"KRW": {
		Code:      "KRW",
		Countries: "South Korea",
		Decimals:  0,
		IsoNum:    410,
		Name:      "South Korean won",
		Symbol:    "₩",
	},
	"KWD": {
		Code:      "KWD",
		Countries: "Kuwait",
		Decimals:  3,
		IsoNum:    414,
		Name:      "Kuwaiti dinar",
		Symbol:    "د.ك",
	},
	"KYD": {
		Code:      "KYD",
		Countries: "Cayman Islands",
		Decimals:  2,
		IsoNum:    136,
		Name:      "Cayman Islands dollar",
		Symbol:    "CI$",
	},
	"KZT": {
		Code:      "KZT",
		Countries: "Kazakhstan",
		Decimals:  2,
		IsoNum:    398,
		Name:      "Kazakhstani tenge",
		Symbol:    "₸",
	},
	"LAK": {
		Code:      "LAK",
		Countries: "Laos",
		Decimals:  2,
		IsoNum:    418,
		Name:      "Lao kip",
		Symbol:    "₭",
	},
	"LBP": {
		Code:      "LBP",
		Countries: "Lebanon",
		Decimals:  2,
		IsoNum:    422,
		Name:      "Lebanese pound",
		Symbol:    "ل.ل.",
	},
	"LKR": {
		Code:      "LKR",
		Countries: "Sri Lanka",
		Decimals:  2,
		IsoNum:    144,
		Name:      "Sri Lankan rupee",
		Symbol:    "Rs",
	},
	"LRD": {
		Code:      "LRD",
		Countries: "Liberia",
		Decimals:  2,
		IsoNum:    430,
		Name:      "Liberian dollar",
		Symbol:    "L$",
	},
	"LSL": {
		Code:      "LSL",
		Countries: "Lesotho",
		Decimals:  2,
		IsoNum:    426,
		Name:      "Lesotho loti",
		Symbol:    "L",
	},
	"LYD": {
		Code:      "LYD",
		Countries: "Libya",
		Decimals:  3,
		IsoNum:    434,
		Name:      "Libyan dinar",
		Symbol:    "LD",
	},
	"MAD": {
		Code:      "MAD",
		Countries: "Morocco, Western Sahara",
		Decimals:  2,
		IsoNum:    504,
		Name:      "Moroccan dirham",
		Symbol:    "DH",
	},
	"MDL": {
		Code:      "MDL",
		Countries: "Moldova",
		Decimals:  2,
		IsoNum:    498,
		Name:      "Moldovan leu",
		Symbol:    "lei",
	},
	"MGA": {
		Code:      "MGA",
		Countries: "Madagascar",
		Decimals:  2,
		IsoNum:    969,
		Name:      "Malagasy ariary",
		Symbol:    "Ar",
	},
	"MKD": {
		Code:      "MKD",
		Countries: "North Macedonia",
		Decimals:  2,
		IsoNum:    807,
		Name:      "Macedonian denar",
		Symbol:    "den",
	},
	"MMK": {
		Code:      "MMK",
		Countries: "Myanmar",
		Decimals:  2,
		IsoNum:    104,
		Name:      "Myanmar kyat",
		Symbol:    "K",
	},
	"MNT": {
		Code:      "MNT",
		Countries: "Mongolia",
		Decimals:  2,
		IsoNum:    496,
		Name:      "Mongolian tögrög",
		Symbol:    "₮",
	},
	"MOP": {
		Code:      "MOP",
		Countries: "Macau",
		Decimals:  2,
		IsoNum:    446,
		Name:      "Macanese pataca",
		Symbol:    "MOP$",
	},
	"MRU": {
		Code:      "MRU",
		Countries: "Mauritania",
		Decimals:  2,
		IsoNum:    929,
		Name:      "Mauritanian ouguiya",
		Symbol:    "UM",
	},
	"MUR": {
		Code:      "MUR",
		Countries: "Mauritius",
		Decimals:  2,
		IsoNum:    480,
		Name:      "Mauritian rupee",
		Symbol:    "₨",
	},
	"MVR": {
		Code:      "MVR",
		Countries: "Maldives",
		Decimals:  2,
		IsoNum:    462,
		Name:      "Maldivian rufiyaa",
		Symbol:    "Rf",
	},
	"MWK": {
		Code:      "MWK",
		Countries: "Malawi",
		Decimals:  2,
		IsoNum:    454,
		Name:      "Malawian kwacha",
		Symbol:    "K",
	},
	"MXN": {
		Code:      "MXN",
		Countries: "Mexico",
		Decimals:  2,
		IsoNum:    484,
		Name:      "Mexican peso",
		Symbol:    "$",
	},
	"MYR": {
		Code:      "MYR",
		Countries: "Malaysia",
		Decimals:  2,
		IsoNum:    458,
		Name:      "Malaysian ringgit",
		Symbol:    "RM",
	},
	"MZN": {
		Code:      "MZN",
		Countries: "Mozambique",
		Decimals:  2,
		IsoNum:    943,
		Name:      "Mozambican metical",
		Symbol:    "MT",
	},
	"NAD": {
		Code:      "NAD",
		Countries: "Namibia",
		Decimals:  2,
		IsoNum:    516,
		Name:      "Namibian dollar",
		Symbol:    "N$",
	},
	"NGN": {
		Code:      "NGN",
		Countries: "Nigeria",
		Decimals:  2,
		IsoNum:    566,
		Name:      "Nigerian naira",
		Symbol:    "₦",
	},
	"NIO": {
		Code:      "NIO",
		Countries: "Nicaragua",
		Decimals:  2,
		IsoNum:    558,
		Name:      "Nicaraguan córdoba",
		Symbol:    "C$",
	},
	"NOK": {
		Code:      "NOK",
		Countries: "Norway, Svalbard and Jan Mayen (SJ), Bouvet Island (BV)",
		Decimals:  2,
		IsoNum:    578,
		Name:      "Norwegian krone",
		Symbol:    "kr",
	},
	"NPR": {
		Code:      "NPR",
		Countries: "Nepal",
		Decimals:  2,
		IsoNum:    524,
		Name:      "Nepalese rupee",
		Symbol:    "रू",
	},
	"NZD": {
		Code:      "NZD",
		Countries: "New Zealand, Cook Islands (CK), Niue (NU), Pitcairn Islands (PN; see also Pitcairn Islands dollar), Tokelau (TK)",
		Decimals:  2,
		IsoNum:    554,
		Name:      "New Zealand dollar",
		Symbol:    "NZ$",
	},
	"OMR": {
		Code:      "OMR",
		Countries: "Oman",
		Decimals:  3,
		IsoNum:    512,
		Name:      "Omani rial",
		Symbol:    "ر.ع.",
	},
	"PAB": {
		Code:      "PAB",
		Countries: "Panama",
		Decimals:  2,
		IsoNum:    590,
		Name:      "Panamanian balboa",
		Symbol:    "B/.",
	},
	"PEN": {
		Code:      "PEN",
		Countries: "Peru",
		Decimals:  2,
		IsoNum:    604,
		Name:      "Peruvian sol",
		Symbol:    "S/",
	},
	"PGK": {
		Code:      "PGK",
		Countries: "Papua New Guinea",
		Decimals:  2,
		IsoNum:    598,
		Name:      "Papua New Guinean kina",
		Symbol:    "K",
	},
	"PHP": {
		Code:      "PHP",
		Countries: "Philippines",
		Decimals:  2,
		IsoNum:    608,
		Name:      "Philippine peso[12]",
		Symbol:    "₱",
	},
	"PKR": {
		Code:      "PKR",
		Countries: "Pakistan",
		Decimals:  2,
		IsoNum:    586,
		Name:      "Pakistani rupee",
		Symbol:    "₨",
	},
	"PLN": {
		Code:      "PLN",
		Countries: "Poland",
		Decimals:  2,
		IsoNum:    985,
		Name:      "Polish złoty",
		Symbol:    "zł",
	},
	"PYG": {
		Code:      "PYG",
		Countries: "Paraguay",
		Decimals:  0,
		IsoNum:    600,
		Name:      "Paraguayan guaraní",
		Symbol:    "₲",
	},
	"QAR": {
		Code:      "QAR",
		Countries: "Qatar",
		Decimals:  2,
		IsoNum:    634,
		Name:      "Qatari riyal",
		Symbol:    "QR",
	},
	"RON": {
		Code:      "RON",
		Countries: "Romania",
		Decimals:  2,
		IsoNum:    946,
		Name:      "Romanian leu",
		Symbol:    "L",
	},
	"RSD": {
		Code:      "RSD",
		Countries: "Serbia",
		Decimals:  2,
		IsoNum:    941,
		Name:      "Serbian dinar",
		Symbol:    "din",
	},
	"RUB": {
		Code:      "RUB",
		Countries: "Russia",
		Decimals:  2,
		IsoNum:    643,
		Name:      "Russian ruble",
		Symbol:    "₽",
	},
	"RWF": {
		Code:      "RWF",
		Countries: "Rwanda",
		Decimals:  0,
		IsoNum:    646,
		Name:      "Rwandan franc",
		Symbol:    "FRw",
	},
	"SAR": {
		Code:      "SAR",
		Countries: "Saudi Arabia",
		Decimals:  2,
		IsoNum:    682,
		Name:      "Saudi riyal",
		Symbol:    "SAR",
	},
	"SBD": {
		Code:      "SBD",
		Countries: "Solomon Islands",
		Decimals:  2,
		IsoNum:    90,
		Name:      "Solomon Islands dollar",
		Symbol:    "SI$",
	},
	"SCR": {
		Code:      "SCR",
		Countries: "Seychelles",
		Decimals:  2,
		IsoNum:    690,
		Name:      "Seychelles rupee",
		Symbol:    "SCR",
	},
	"SDG": {
		Code:      "SDG",
		Countries: "Sudan",
		Decimals:  2,
		IsoNum:    938,
		Name:      "Sudanese pound",
		Symbol:    "SS£",
	},
	"SEK": {
		Code:      "SEK",
		Countries: "Sweden",
		Decimals:  2,
		IsoNum:    752,
		Name:      "Swedish krona/kronor",
		Symbol:    "kr",
	},
	"SGD": {
		Code:      "SGD",
		Countries: "Singapore",
		Decimals:  2,
		IsoNum:    702,
		Name:      "Singapore dollar",
		Symbol:    "S$",
	},
	"SHP": {
		Code:      "SHP",
		Countries: "Saint Helena (SH-SH), Ascension Island (SH-AC), Tristan da Cunha",
		Decimals:  2,
		IsoNum:    654,
		Name:      "Saint Helena pound",
		Symbol:    "£",
	},
	"SLL": {
		Code:      "SLL",
		Countries: "Sierra Leone",
		Decimals:  2,
		IsoNum:    694,
		Name:      "Sierra Leonean leone",
		Symbol:    "Le",
	},
	"SOS": {
		Code:      "SOS",
		Countries: "Somalia",
		Decimals:  2,
		IsoNum:    706,
		Name:      "Somali shilling",
		Symbol:    "Sh.So.",
	},
	"SRD": {
		Code:      "SRD",
		Countries: "Suriname",
		Decimals:  2,
		IsoNum:    968,
		Name:      "Surinamese dollar",
		Symbol:    "SR$",
	},
	"SSP": {
		Code:      "SSP",
		Countries: "South Sudan",
		Decimals:  2,
		IsoNum:    728,
		Name:      "South Sudanese pound",
		Symbol:    "SS£",
	},
	"STN": {
		Code:      "STN",
		Countries: "São Tomé and Príncipe",
		Decimals:  2,
		IsoNum:    930,
		Name:      "São Tomé and Príncipe dobra",
		Symbol:    "Db",
	},
	"SVC": {
		Code:      "SVC",
		Countries: "El Salvador",
		Decimals:  2,
		IsoNum:    222,
		Name:      "Salvadoran colón",
		Symbol:    "₡",
	},
	"SYP": {
		Code:      "SYP",
		Countries: "Syria",
		Decimals:  2,
		IsoNum:    760,
		Name:      "Syrian pound",
		Symbol:    "LS",
	},
	"SZL": {
		Code:      "SZL",
		Countries: "Eswatini",
		Decimals:  2,
		IsoNum:    748,
		Name:      "Swazi lilangeni",
		Symbol:    "L",
	},
	"THB": {
		Code:      "THB",
		Countries: "Thailand",
		Decimals:  2,
		IsoNum:    764,
		Name:      "Thai baht",
		Symbol:    "฿",
	},
	"TJS": {
		Code:      "TJS",
		Countries: "Tajikistan",
		Decimals:  2,
		IsoNum:    972,
		Name:      "Tajikistani somoni",
		Symbol:    "SM",
	},
	"TMT": {
		Code:      "TMT",
		Countries: "Turkmenistan",
		Decimals:  2,
		IsoNum:    934,
		Name:      "Turkmenistan manat",
		Symbol:    "T",
	},
	"TND": {
		Code:      "TND",
		Countries: "Tunisia",
		Decimals:  3,
		IsoNum:    788,
		Name:      "Tunisian dinar",
		Symbol:    "DT",
	},
	"TOP": {
		Code:      "TOP",
		Countries: "Tonga",
		Decimals:  2,
		IsoNum:    776,
		Name:      "Tongan paʻanga",
		Symbol:    "T$",
	},
	"TRY": {
		Code:      "TRY",
		Countries: "Turkey",
		Decimals:  2,
		IsoNum:    949,
		Name:      "Turkish lira",
		Symbol:    "₺",
	},
	"TTD": {
		Code:      "TTD",
		Countries: "Trinidad and Tobago",
		Decimals:  2,
		IsoNum:    780,
		Name:      "Trinidad and Tobago dollar",
		Symbol:    "TT$",
	},
	"TWD": {
		Code:      "TWD",
		Countries: "Taiwan",
		Decimals:  2,
		IsoNum:    901,
		Name:      "New Taiwan dollar",
		Symbol:    "NT$",
	},
	"TZS": {
		Code:      "TZS",
		Countries: "Tanzania",
		Decimals:  2,
		IsoNum:    834,
		Name:      "Tanzanian shilling",
		Symbol:    "TSh",
	},
	"UAH": {
		Code:      "UAH",
		Countries: "Ukraine",
		Decimals:  2,
		IsoNum:    980,
		Name:      "Ukrainian hryvnia",
		Symbol:    "₴",
	},
	"UGX": {
		Code:      "UGX",
		Countries: "Uganda",
		Decimals:  0,
		IsoNum:    800,
		Name:      "Ugandan shilling",
		Symbol:    "USh",
	},
	"USD": {
		Code:      "USD",
		Countries: "United States, American Samoa (AS), British Indian Ocean Territory (IO) (also uses GBP), British Virgin Islands (VG), Caribbean Netherlands (BQ – Bonaire, Sint Eustatius and Saba), Ecuador (EC), El Salvador (SV), Guam (GU), Haiti (HT), Marshall Islands (MH), Federated States of Micronesia (FM), Northern Mariana Islands (MP), Palau (PW), Panama (PA) (as well as Panamanian Balboa), Puerto Rico (PR), Timor-Leste (TL), Turks and Caicos Islands (TC), U.S. Virgin Islands (VI), United States Minor Outlying Islands (UM)",
		Decimals:  2,
		IsoNum:    840,
		Name:      "United States dollar",
		Symbol:    "$",
	},
	"UYU": {
		Code:      "UYU",
		Countries: "Uruguay",
		Decimals:  2,
		IsoNum:    858,
		Name:      "Uruguayan peso",
		Symbol:    "$",
	},
	"UZS": {
		Code:      "UZS",
		Countries: "Uzbekistan",
		Decimals:  2,
		IsoNum:    860,
		Name:      "Uzbekistan som",
		Symbol:    "soʻm",
	},
	"VES": {
		Code:      "VES",
		Countries: "Venezuela",
		Decimals:  2,
		IsoNum:    928,
		Name:      "Venezuelan bolívar soberano",
		Symbol:    "Bs.S.",
	},
	"VND": {
		Code:      "VND",
		Countries: "Vietnam",
		Decimals:  0,
		IsoNum:    704,
		Name:      "Vietnamese đồng",
		Symbol:    "₫",
	},
	"VUV": {
		Code:      "VUV",
		Countries: "Vanuatu",
		Decimals:  0,
		IsoNum:    548,
		Name:      "Vanuatu vatu",
		Symbol:    "VT",
	},
	"WST": {
		Code:      "WST",
		Countries: " Samoa",
		Decimals:  2,
		IsoNum:    882,
		Name:      "Samoan tal",
		Symbol:    "WS$",
	},
	"XAF": {
		Code:      "XAF",
		Countries: "BEAC Cameroon (CM), Central African Republic (CF), Republic of the Congo (CG), Chad (TD), Equatorial Guinea (GQ), Gabon (GA)",
		Decimals:  0,
		IsoNum:    950,
		Name:      "CFA franc",
		Symbol:    "FCFA",
	},
	"XAG": {
		Code:      "XAG",
		Countries: "",
		Decimals:  0,
		IsoNum:    961,
		Name:      "Silver (one troy ounce)",
		Symbol:    "",
	},
	"XAU": {
		Code:      "XAU",
		Countries: "",
		Decimals:  0,
		IsoNum:    959,
		Name:      "Gold (one troy ounce)",
		Symbol:    "",
	},
	"XBA": {
		Code:      "XBA",
		Countries: "",
		Decimals:  0,
		IsoNum:    955,
		Name:      "European Composite Unit (EURCO) (bond market unit)",
		Symbol:    "",
	},
	"XBB": {
		Code:      "XBB",
		Countries: "",
		Decimals:  0,
		IsoNum:    956,
		Name:      "European Monetary Unit (E.M.U.-6) (bond market unit)",
		Symbol:    "",
	},
	"XBC": {
		Code:      "XBC",
		Countries: "",
		Decimals:  0,
		IsoNum:    957,
		Name:      "European Unit of Account 9 (E.U.A.-9) (bond market unit)",
		Symbol:    "",
	},
	"XBD": {
		Code:      "XBD",
		Countries: "",
		Decimals:  0,
		IsoNum:    958,
		Name:      "European Unit of Account 17 (E.U.A.-17) (bond market unit)",
		Symbol:    "",
	},
	"XCD": {
		Code:      "XCD",
		Countries: " Anguilla (AI), Antigua and Barbuda (AG), Dominica (DM), Grenada (GD), Montserrat (MS), Saint Kitts and Nevis (KN), Saint Lucia (LC), Saint Vincent and the Grenadines (VC)",
		Decimals:  2,
		IsoNum:    951,
		Name:      "East Caribbean dolla",
		Symbol:    "$",
	},
	"XOF": {
		Code:      "XOF",
		Countries: "BCEAO Benin (BJ), Burkina Faso (BF), Côte d'Ivoire (CI), Guinea-Bissau (GW), Mali (ML), Niger (NE), Senegal (SN), Togo (TG)",
		Decimals:  0,
		IsoNum:    952,
		Name:      "CFA franc",
		Symbol:    "CFA",
	},
	"XPD": {
		Code:      "XPD",
		Countries: "",
		Decimals:  0,
		IsoNum:    964,
		Name:      "Palladium (one troy ounce)",
		Symbol:    "",
	},
	"XPF": {
		Code:      "XPF",
		Countries: "French territories of the Pacific Ocean: French Polynesia (PF), New Caledonia (NC), Wallis and Futuna (WF)",
		Decimals:  0,
		IsoNum:    953,
		Name:      "CFP franc (franc Pacifique)",
		Symbol:    "F",
	},
	"XPT": {
		Code:      "XPT",
		Countries: "",
		Decimals:  0,
		IsoNum:    962,
		Name:      "Platinum (one troy ounce)",
		Symbol:    "",
	},
	"XSU": {
		Code:      "XSU",
		Countries: "",
		Decimals:  0,
		IsoNum:    994,
		Name:      "SUCRE Unified System for Regional Compensation (SUCRE)",
		Symbol:    "",
	},
	"XTS": {
		Code:      "XTS",
		Countries: "",
		Decimals:  0,
		IsoNum:    963,
		Name:      "Code reserved for testing",
		Symbol:    "",
	},
	"XUA": {
		Code:      "XUA",
		Countries: "",
		Decimals:  0,
		IsoNum:    965,
		Name:      "ADB Unit of Account African Development Bank",
		Symbol:    "",
	},
	"XXX": {
		Code:      "XXX",
		Countries: "",
		Decimals:  0,
		IsoNum:    999,
		Name:      "No currency",
		Symbol:    "",
	},
	"YER": {
		Code:      "YER",
		Countries: "Yemen",
		Decimals:  2,
		IsoNum:    886,
		Name:      "Yemeni rial",
		Symbol:    "ر.ي",
	},
	"ZAR": {
		Code:      "ZAR",
		Countries: "Lesotho, Namibia, South Africa",
		Decimals:  2,
		IsoNum:    710,
		Name:      "South African rand",
		Symbol:    "R",
	},
	"ZMW": {
		Code:      "ZMW",
		Countries: "Zambia",
		Decimals:  2,
		IsoNum:    967,
		Name:      "Zambian kwacha",
		Symbol:    "K",
	},
	"ZWL": {
		Code:      "ZWL",
		Countries: "Zimbabwe",
		Decimals:  2,
		IsoNum:    932,
		Name:      "Zimbabwean dollar",
		Symbol:    "$",
	},
}
